### ISSUE TITLE
please transfer bots from personal account to a github-organisation to allow better cooperation

### ISSUE THREAD

**Issue by lw-schick** [eppye-bots/bots#380] opened 2016-08-22 15:49 UTC
I recently fixed a bug and made a pull request for it (#374), but i realized after a while that no one reacts... So I contacted Ebbers. Answer:

```
please do not use dev version.
bots 3.2 is stable release, via sourceforge.

I do not do pull requests.

kind regards,
Henk-Jan Ebbers
```

So that means for me that bots seams to be dead ... the main developer don't like contributions any more...

So can someone please create a fork where we can contribute to get the bots community to live again? In my eyes there is a lot of work still left. F.e. compatibility to newer versions of python and modules, backend upgrade etc.

I don't think that I have enough knowledge in bots to do this task...

**Comment by JCapriotti** [comment] 2016-08-22 17:07
I agree, it'd be nice to have a better community of contributors. One question though... is it possible the phrase "pull request" was simply misunderstoood?

When I read that, [this thread](https://groups.google.com/d/msg/botsmail/nu0CZHc6IDM/OLKkkayAEgAJ) about wiki vs RTD popped into my head:

    Abhishek Ram
    > I have created a PR #367 with the sphix docs, take a look and see how it is.
    
    eppye
    > great! 
    > where can I watch it? 
    
    Abhishek Ram
    > I have mentioned the steps in the PR, just clone the branch to your computer 
    > and follow the steps mentioned. 

Maybe I'm wrong and he really doesn't do (accept?) pull requests... but the bottom two lines are why I am not sold.

That said...  this repo does seem very silent. I'd be willing to help, but I wouldn't have the time to be fully engaged.

**Comment by WouterVH** [comment] 2016-09-17 11:22
> please do not use dev version.

I only use dev-version + setuptools-support I added in my fork. 
Otherwise it's painfull to install.


> So can someone please create a fork where we can contribute to get the bots community to live again?

I propose to create a "bots-project" organisation on github, if Henk-Jan would agree to this.

**Comment by BikeMikeAU** [comment] 2016-09-18 00:05
Previously all changes were handled through the mailing list and Google Code issues list. The project is only on Github because GC shut down, but the Google mailing list is still active. You can submit suggestions and changes there. Certainly nearly all of my past changes since v1.5 to v3.2 have been accepted and are now part of the product.
The number one requirement for an EDI platform is stability and reliability, so regular new versions are not a priority for me. There's nothing I can't do with Bots right now (either standard or with user scripting), and no significant bugs I'm aware of.

**Comment by WouterVH** [comment] 2016-09-19 00:17
The problem is that nothing is happening anymore since v3.2.0.

**Comment by lw-schick** [comment] 2016-09-29 15:48
@BikeMikeAU Thank you for the tip with the mailing list.

You are right with the fact that a EDI platform needs stability and reliability. But I also need an active development and a active community where I can bring in my suggestions and optimizations.

Think on the Linux Kernel witch is stable, reliable, and has an active community.

As a relatively new user I get a bit confused:
- there is a shut down Google Code side
- there is a new github fork with dead links in the Readme, no tagging, no milestones and a bad wiki.
- there is an old version 3.2 on sourceforge.net (yet another platform) which was released 2 years ago

I wonder why the issues and pull requests are activated when they should be done via the mailing list.

I would recommend to:
- close the old Google Code side
- build a new "welcome" site (f.e. a new, nice github readme page - [look here](https://github.com/matiassingers/awesome-readme))
- make a place where a community can grow and contribute to new versions (f.e. github)

That has not to be a burden to personal live. When we would use unit tests, we could use [Travis CI](https://docs.travis-ci.com/user/languages/python/) to automatically check pull requests to ensure stability and reliability.

**Comment by WouterVH** [comment] 2016-09-29 17:42
i'm willing to help out.

The first thing we need to is to transfer, not fork, 
the bots from this user-account to an organisation-account.
Henk-Jan needs to do this, otherwise we create just another fork.

please see
https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

**Comment by WouterVH** [comment] 2016-09-29 17:44
maybe adjust the title of this issue:

eppye-bots is dead, please create a fork
->
please transfer to bots from personal account to a github-organisation to allow better cooperation

**Comment by WouterVH** [comment] 2016-09-30 13:17
I went ahead and create a gthub-organisation account called "bots-edi", since "bots" was already taken.

I already invited  @eppye-bots  @lw-schick  to co-manage this account.
Anybody else interested?

**Comment by djfurman** [comment] 2016-09-30 15:01
Happy to contribute.

**Comment by WouterVH** [comment] 2016-09-30 15:28
@djfurman ,  I've sent you an invite.

**Comment by JCapriotti** [comment] 2016-09-30 18:00
I've been following the discussion and thought it would be good to get input from Henk-Jan. Since using GitHub for this didn't seem to be getting us anywhere, I started this thread in Google Groups yesterday:
https://groups.google.com/forum/#!topic/botsmail/9dfik6NxDzM

That said, open source projects fork for valid reasons all the time....

**Comment by WouterVH** [comment] 2016-10-01 14:16
What is difficult on replying to messages posted in github?

I want to reply on the mailinglijst, but I can't until my membership to the group is approved. :(
Maybe I'll try again next week.

My urgent issues with bots
 - it's not installable
 - it does not declare its dependencies
 - no releases on pypi
- impossible to install in develop-mode
- puts everything (data, log-files, database-files, ...) in site-packages

I'm interested to help cleanup this mess.
I'm less interested in developing new features in bots itself.

**Comment by djfurman** [comment] 2016-10-01 14:23
Thanks for the invite @WouterVH

**Comment by WouterVH** [comment] 2016-10-02 14:07
Yesterday my membership to the google-mailinglist was approved,
but 24 hours laters, I still do not see the reply I posted to the topic started by @JCapriotti.
The messages seems to subject to manual approval as well.

Here is  the message I  posted yesterday:

 ```
Hello everyone


I recently started supporting bots-installations
Here is are some primary issues I encounter:

1) "bots 3.2 was released 2014-09-02."

When looking for python-packages, pypi.org is default location to find them.
There we find bots v3.0.0 at https://pypi.python.org/pypi/bots-open-source-edi-translator/
So as pypi is concerned, bots v3.2 does not exist.

2) As a consequence bots is not installable via pip and other tools
   You need to find it in an obscure location, manually download

3) bots is not installable in develop-mode, since it does not support setuptools

4) bots does not declare its dependencies in setup.py,
   you manually have to search them together and install them.


All of these issues are unnecessary.

I completely understand, and respect, that Henk-Jan does not have the time to fix these issues.
But we can do better than creating new forks all the time by anyone who wants to fix something.


So here is the plan:

- Moving from google to github was a great idea.
  But migration is not completed, since many urls reference the old site.
  Me and others can help with this, but then we need write-access.

- I propose that the bots-project moves from the personal account of Henk-Jan
  to a gitlab-organisation.
  For this I registered "bots-edi"-organisation, since "bots" is already taken by an unrelated user.
  see https://github.com/bots-edi

  There can be multiple admins for this project, so that Henk-Jan can *delegate* tasks he is not familiar with.
  Some domains as example:
   - complete migration
   - python-packaging
   - documentation sphinx/wiki
   - setup continuous integration
   - managing pull-requests

Objections anyone?
```

**Comment by djfurman** [comment] 2016-10-02 15:07
Makes sense to me. Should we log each as an issue under the new
organization and start working them through pull requests?

I've done some work on requirements.txt for dependency installation through
pip, so I'm happy to share. But it's not full deployment yet.

I also want to open a discussion on implementation best practices for
production. I'm happy to share mine but I'm sure we can improve on them
overall 😎.

**Comment by WouterVH** [comment] 2016-10-02 15:51
we'll needs some admins to do pull-requests, since Henk-Jan is not familiar with it.

**Comment by JCapriotti** [comment] 2016-10-04 14:40
Thanks @lw-schick for the invite. Just curious... am I correct that there are no repositories in @bots-edi? I was hoping to create an issue or two (basically, deployment-related enhancement ideas), but didn't see any repos.

FWIW, I have limited EDI background, but have been making a lot of progress digging through Bots channels, routes, etc. My biggest contribution would probably be in the area of deployment automation and maybe testing automation.

**Comment by WouterVH** [comment] 2016-10-05 01:16
> am I correct that there are no repositories in @bots-edi?

My idea was that Henk-Jan would click on two buttons to transfer the repository, 
instead of us creating a fork.

Projects -> Settings  -> (scroll down) Transfer 
 - Type the name of the repository to confirm  --> "bots"
 - New owner’s GitHub username or organization name  --> "bots-edi"


Now I notice new messages appear on the discussion-topic in the googlemail after I posted a long reply 4 days ago.

Is my message being censored?
This is getting more than annoying.



I just posted a new question to the mailinggroup titled "Is this a moderated group?":
```
Hi
I registered Saturday on this list, and posted a message that I'm still not seeing 4 days later.
Does every email to this list need manual approval of a moderator?

regards
Wouter vanden Hove
```

**Comment by WouterVH** [comment] 2016-10-05 10:31
I'll transferring the bots-code from my repo to bots-edi and renamed it into "bots-tmp"
see  https://github.com/bots-edi/bots-tmp

**Comment by JCapriotti** [comment] 2016-10-05 14:09
Cool, thanks.

While not ideal, a fork is probably fine. Open source things fork all the time for various reasons.

**Comment by lw-schick** [comment] 2016-10-05 15:10
Can someone create a gitter community for bots so we can talk about how we should manage the fork...?

**Comment by WouterVH** [comment] 2016-10-06 17:02
I never used gitter before, but I created a bots-edi community:
https://gitter.im/bots-edi/

**Comment by WouterVH** [comment] 2016-10-07 08:50
Correct URL: https://gitter.im/bots-edi/Lobby

**Closed** 2016-12-12 20:52 UTC
